spring:
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE
server:
  port: 8085